### ISSUE TITLE
Add some interactive features into your styling ... such as in your navigation links

### ISSUE THREAD

**Issue by mizutombo** [nthugon/portfolio#21]
To improve the styling of your blog webpage, I recommend that you incorporate interactive features into your CSS coding to improve your users' experience with the interface. For example, enable the navigation links to change color when the user mouses over the link or clicks on the link. Similarly, you could code live links into your articles that would take the user to the actual article, either as a tab in the webpage, or in a new window. 

These styling changes for active link anchors can be incorporated into your CSS code scripts.

**Comment by nthugon** [comment]
I added a change in background-color on hover for nav links.

`.nav-list li:hover {
  background-color: #e3f7e3;
  border-radius: 15px;
}`
